substitutions:
  #general settings
  host_name: as-example
  device_name: as_example
  device_name_upper: as.example
  status_led_interval_ok: 10s
  status_led_interval_booting: 3s
  settings_log_level: DEBUG
  settings_flash_write_interval: 1min
  
  # MQTT Settings
  mqtt_discovery: "false"
  
  #I2C Bus
  i2c_bus_a_name: i2c_bus_a
  i2c_bus_a_sda: GPIO23
  i2c_bus_a_scl: GPIO22

  # webserver
  web_server_ota_active: "true"
  
  # EZO settings
  max_retry_attempts: "4"
  default_temp_comp_value: "25"
  
  # EZO Enable Pins
  enable_rtd_pin: GPIO33
  enable_ec_pin: GPIO12
  enable_ph_pin: GPIO13
  
  entities_internal: "false"
  
  # EZO sample intervals
  min_sample_interval_ec: "1000" # 1s
  initial_sample_interval_ec: "1000" # 1s
  max_sample_interval_ec: "60000" # 1min
  sliding_window_size_ec: "10"
  sliding_window_send_every_ec: "5"
    
  min_sample_interval_ph: "1000" # 1s
  initial_sample_interval_ph: "1000" # 1s
  max_sample_interval_ph: "60000" # 1min
  sliding_window_size_ph: "10"
  sliding_window_send_every_ph: "5"
  
  min_sample_interval_rtd: "1000" # 1s
  initial_sample_interval_rtd: "1000" # 1s
  max_sample_interval_rtd: "60000" # 1min
  sliding_window_size_rtd: "10"
  sliding_window_send_every_rtd: "5"
  
  min_sample_interval_ec_tempcomp: "10000" #1min
  initial_sample_interval_ec_tempcomp: "10000" #1min
  max_sample_interval_ec_tempcomp: "3600000" #1h
  
  min_sample_interval_ph_tempcomp: "10000" #1min 
  initial_sample_interval_ph_tempcomp: "10000" #1min 
  max_sample_interval_ph_tempcomp: "3600000" #1h
  
  # MQTT sample intervals
  min_mqtt_interval_ec: "6000" # 1s
  initial_mqtt_interval_ec: "6000" # 1s
  max_mqtt_interval_ec: "3600000" #1h
  
  min_mqtt_interval_ph: "6000" # 1s
  initial_mqtt_interval_ph: "6000" # 1s
  max_mqtt_interval_ph: "3600000" #1h
  
  min_mqtt_interval_rtd: "6000" # 1s
  initial_mqtt_interval_rtd: "6000" # 1s
  max_mqtt_interval_rtd: "3600000" #1h
  
  min_mqtt_interval_combined: "6000" # 1s
  initial_mqtt_interval_combined: "6000" # 1s
  max_mqtt_interval_combined: "3600000" #1h

  mqtt_rtd_enabled: "true"
  mqtt_ec_enabled: "true"
  mqtt_ph_enabled: "true"
  mqtt_combined_enabled: "true"
  
  mqtt_entities_internal: "false"
  
esphome:
  name: ${host_name}
  platform: ESP32
  board: esp32dev
  
packages:
  common_api: !include /config/esphome/esphome-common/api.yaml
  common_base: !include /config/esphome/esphome-common/base.yaml
  common_status: !include /config/esphome/esphome-common/status.yaml
  common_restart: !include /config/esphome/esphome-common/restart.yaml
  common_i2c_bus_a: !include /config/esphome/esphome-common/i2c_bus_a.yaml
  common_web_server: !include /config/esphome/esphome-common/web_server.yaml
  as_hydroponics_kit_as_ezo: !include /config/esphome/esphome-ashydroponicskit/as_ezo.yaml